@Library('tci-library') _
import tci.jobs.ci.baseMavenCIJob

pipeline {
    agent { label 'tci-jnlp-node' }
    stages {
        stage ("Winter Is Coming") {
            steps {
                script {
                    def ciJob = new baseMavenCIJob(this)
                    ciJob.subDir = 'apps/maven-app'
                    ciJob.setVersion = true
                    ciJob.version = "1.0.0"
                    ciJob.run()
                }
            }
        }
    }
}
